pool:
  vmImage: 'ubuntu-18.04' 

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)       

steps:
- script: docker build -t $(dockerId)/$(imageName)

steps:
- script: docker login -u $(dockerId) -p $(pswd) 

