pool:
  vmImage: 'ubuntu-18.04' 

steps:
- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker build -t $(dockerId)/$(imageName) .
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)       

