variables:
- group: Infrastructure-Variables-EPAM-1
steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure Web App Service Deploy'
  inputs:
    azureSubscription: $(subscription-id)
    appType: webAppContainer
    WebAppName: $(webapp-name)
    DockerNamespace: index.docker.io
    DockerRepository: $(repository-name)
    DockerImageTag: $(tag-name)




