variables:
- group: Infrastructure-Variables-EPAM-2
steps:
# Build Image and push to registry
- task: Docker@2
  displayName: BuildnPush
  inputs:
    # Azure Devops Connected Docker Hub Registry
    containerRegistry: $(registry-name)
    # Docker Hub Repository
    repository: $(repository-name)
    tags: latest

# Deploy to cluster (requires service connection and deployed cluster)
- task: Kubernetes@1
  displayName: 'Deploy to Cluster'
  inputs:
    kubernetesServiceEndpoint: 'aks-connect-delete'
    command: apply
    arguments: -f deploy/k8-attributes.yaml

