variables:
- group: Infrastructure-Variables-EPAM-2
steps:
# Build docker image
- task: Docker@2
  displayName: BuildnPush
  inputs:
    # Azure Devops Connected Docker Hub Registry
    containerRegistry: $(registry-name)
    # Docker Hub Repository
    repository: $(repository-name)
    tags: latest

# Deploy to cluster
- task: Kubernetes@1
  displayName: 'Deploy to Cluster'
  inputs:
    kubernetesServiceEndpoint: 'azure-aks-connect-delete'
    namespace: default
    command: apply
    arguments: -f deploy/k8/k8-attributes.yaml

