apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: flask
    tier: frontend
spec:
  selector:
    app: flask
    tier: frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000